NorthwindMVC.Web/Controllers/LanguageController.cs
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace NorthwindMVC.Web.Controllers
{
    public class LanguageController : Controller
    {
        public IActionResult ChangeLanguage(string culture)
        {
            Response.Cookies.Append(CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions() { Expires = DateTimeOffset.UtcNow.AddYears(1) });

            return Redirect(Request.Headers["Referer"].ToString());
        }
    }
}

NorthwindMVC.Web/Controllers/ToastController.cs
using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using NorthwindMVC.Web.Helpers.ToastNotifications;

namespace NorthwindMVC.Web.Controllers
{
    public class ToastController : Controller
    {
        private readonly ITempDataDictionary _tempData;

        public ToastController(IHttpContextAccessor httpContextAccessor, ITempDataDictionaryFactory tempData) 
        {
            _tempData = tempData.GetTempData(httpContextAccessor.HttpContext);
        }
        public IActionResult GetMessage()
        {
            if (!_tempData.TryGetValue(Toastr.Key, out var text))
                return Ok(string.Empty);

            var htmlString = new HtmlString($"{text}");
            if (htmlString.Value == null)
                return Ok(string.Empty);

            _tempData.Remove(Toastr.Key);

            return Ok(htmlString.ToString());
        }
    }
}

NorthwindMVC.Web/Controllers/UserController.cs
using FluentValidation;
using FluentValidation.Results;
using MapsterMapper;
using Microsoft.AspNetCore.Mvc;
using NorthwindMVC.Core;
using NorthwindMVC.Services;
using NorthwindMVC.Web.Helpers.PasswordHelper;
using NorthwindMVC.Web.ViewModels;
using System.Text.Json;

namespace NorthwindMVC.Web.Controllers
{
    public class UserController : Controller

    {
        private readonly IUserService _userService;
        private readonly IValidator<UserViewModel> _validator;
        private readonly IMapper _mapper;

        public UserController(IUserService UserService,
                              IValidator<UserViewModel> validator,
                              IMapper Mapper)
        {
            _userService = UserService;
            _validator = validator;
            _mapper = Mapper;
        }


        public IActionResult Index()
        {
            return View("LogIn");
        }

        [HttpGet]
        public IActionResult LogIn()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult LogOut()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LogInAsync(UserLogInViewModel model)
        {
            ModelState.Clear();
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Provide username/email or passowrd.");
                return View(model);
            }

            var user = await _userService.GetByUsernameOrEmail(model.UsernameOrEmail);
            if (user == null || model.Password == null)
            {
                ModelState.AddModelError(string.Empty, "Password or username/email incorrect!");
                return View(model);
            }

            var passwordHash = PasswordHelper.CreateHash(model.Password, user.PasswordSalt);
            if (user.PasswordHash != passwordHash)
            {
                ModelState.AddModelError(string.Empty, "Password or username/email incorrect!");
                return View(model);
            }
            string jsonString = JsonSerializer.Serialize(model);
            HttpContext.Session.SetString("UserData", jsonString);

            TempData["SuccessLogin"] = "You've been successfully logged in!";
            return RedirectToAction("Index", "Home");
        }

        public IActionResult SignUp()
        {
            return View("SignUp");
        }

        [HttpPost]
        public async Task<IActionResult> SignUp(UserViewModel model)
        {
            ModelState.Clear();
            ValidationResult result = await _validator.ValidateAsync(model);

            if (!result.IsValid)
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                }
                return View(model);
            }

            var passwordSalt = PasswordHelper.CreateSalt();
            var passwordHash = PasswordHelper.CreateHash(model.Password, passwordSalt);

            var entity = new User()
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                DateOfBirth = model.DateOfBirth,
                Username = model.Username,
                Email = model.Email,
                PasswordHash = passwordHash,
                PasswordSalt = passwordSalt,
            };

            await _userService.Add(entity);

            return RedirectToAction("Index", "Home");
        }
    }
}

NorthwindMVC.Web/Views/Shared/_Layout.cshtml
@using System;
@using NorthwindMVC.Services;
@using NorthwindMVC.Web.Helpers.ToastNotifications;

@inject LanguageService LanguageService;
@inject IToastr Toastr;

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NorthwindMVC</title>

    <!-- Styles -->
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Select2 -->
    <link rel="stylesheet" href="~/plugins/select2/css/select2.min.css">
    <!-- Tempus Dominus -->
    <link rel="stylesheet" href="~/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="~/plugins/jqvmap/jqvmap.min.css">
    <!-- Daterange Picker -->
    <link rel="stylesheet" href="~/plugins/daterangepicker/daterangepicker.css">
    <!-- Summernote -->
    <link rel="stylesheet" href="~/plugins/summernote/summernote-bs4.min.css">
    <!-- Overlay Scrollbars -->
    <link rel="stylesheet" href="~/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- AdminLTE -->
    <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
    <!-- Flags -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lipis/flag-icons@7.2.3/css/flag-icons.min.css">
    <!-- Toastr -->
    <link rel="stylesheet" href="~/plugins/toastr/toastr.min.css">
    <!-- Custom Styles -->
    <link rel="stylesheet" href="~/css/context-menu.css" />

    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI -->
    <script src="~/plugins/jquery-ui/jquery-ui.min.js"></script>
    <script>
        $.widget.bridge('uibutton', $.ui.button);
    </script>

    <!-- InputMask -->
    <script src="~/plugins/moment/moment.min.js"></script>
    <script src="~/plugins/inputmask/jquery.inputmask.min.js"></script>

</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Navbar Left -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
            </ul>
            <!-- Navbar Right -->
            <ul class="navbar-nav ml-auto">
                <div class="navbar-nav ml-auto">
                    <div class="dropdown">
                        <a class="dropdown-toggle" href="#" role="button" id="languageDropdown" data-toggle="dropdown" aria-expanded="false">
                            <i class="fi fi-@LanguageService.GetCurrentLanguage()"></i> @LanguageService.GetCurrentLanguage()
                        </a>
                        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                            <a asp-controller="Language" asp-action="ChangeLanguage" asp-route-culture="en-US" class="dropdown-item">
                                <i class="fi fi-us fis"></i> @Translate["English"]
                            </a>
                            <div class="dropdown-divider"></div>
                            <a asp-controller="Language" asp-action="ChangeLanguage" asp-route-culture="bs-Latn-BA" class="dropdown-item">
                                <i class="fi fi-ba fis"></i> @Translate["Bosnian"]
                            </a>
                        </div>
                    </div>
                </div>
            </ul>
        </nav>
        <!-- Sidebar -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <a href="@Url.Action("Index", "Home")" class="brand-link">
                <img src="~/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">NorthWind-MVC</span>
            </a>
            <div class="sidebar">
                <!-- Sidebar Navigation -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="Home" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>@Translate["Home"]</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="Employee" class="nav-link">
                                <i class="nav-icon fas fa-users"></i>
                                <p>@Translate["Employees"]</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon 	fas fa-balance-scale"></i>
                                <p>
                                    @Translate["Products"]
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-action="Index" asp-controller="Product" class="nav-link">
                                        <i class="fas fa-boxes nav-icon"></i>
                                        <p>@Translate["Products"]</p>
                                    </a>
                                </li>                              
                                <li class="nav-item">
                                    <a asp-action="Index" asp-controller="Category" class="nav-link">
                                        <i class="fas fa-expand-arrows-alt nav-icon"></i>
                                        <p>@Translate["Categories"]</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="Shipper" class="nav-link">
                                <i class="nav-icon fas fa-shipping-fast"></i>
                                <p>@Translate["Shippers"]</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="Supplier" class="nav-link">
                                <i class="nav-icon fas fa-boxes"></i>
                                <p>@Translate["Supplyers"]</p>
                            </a>
                        </li>
                    </ul>
                    
                </nav>
                <!-- Logout -->
                <form asp-action="Logout" asp-controller="User">
                    <button class="btn btn-secondary" style="position: absolute; bottom: 20px; left: 20px; right: 20px;">
                        <i class="fas fa-sign-out-alt"></i> @Translate["LogOut"]
                    </button>
                </form>
            </div>
        </aside>
        <!-- Content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0">@Translate["Home"]</h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">@Translate["Home"]</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <main role="main" class="content">
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </main>
        </div>
        <!-- Footer -->
        <footer class="main-footer">
            <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
            All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
                <b>Version</b> 3.2.0
            </div>
        </footer>
    </div>
    <!-- Scripts -->
    
    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/plugins/bs-custom-file-input/bs-custom-file-input.min.js"></script>

    <!-- Moment.js -->
    <script src="~/plugins/moment/moment.min.js"></script>
    <!-- Tempus Dominus -->
    <script src="~/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Select2 -->
    <script src="~/plugins/select2/js/select2.full.min.js"></script>
    <!-- Other Plugins -->
    <script src="~/plugins/chart.js/Chart.min.js"></script>
    <script src="~/plugins/sparklines/sparkline.js"></script>
    <script src="~/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="~/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <script src="~/plugins/jquery-knob/jquery.knob.min.js"></script>
    <script src="~/plugins/daterangepicker/daterangepicker.js"></script>
    <script src="~/plugins/summernote/summernote-bs4.min.js"></script>
    <script src="~/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE -->
    <script src="~/dist/js/adminlte.js"></script>
    <!-- Custom Scripts -->
    <script src="~/js/context-menu.js"></script>
    <!-- Toastr -->
    <script src="~/plugins/toastr/toastr.min.js"></script>
    <script>
        function showToastMessages(timeout = 0) {
            return new Promise(function (resolve) {
                setTimeout(async function () {
                    await $.get("@Url.Action("GetMessages", "Toast")",
                        function (jsResult) {
                            eval(jsResult);
                            resolve("Ok");
                        });
                },
                    timeout);
            });
        };
    </script>
    <script>
        $(document).ready(function () {
            $('[data-mask]').inputmask();
        });
    </script>
    @Toastr.Display()
    @await RenderSectionAsync("Scripts", required: false)
</body>